Enable ZC Direct API for multicore builds to support the refactored ZC EM API
This commit removes the unused ZC EM API from multicore builds.
Additionally, this commit resolves the multicore build failure
seen in last night's autobuild.

Error message:
../../../../bin/charmc -g -Werror=vla  -o lbObject.o lbObject.C
/scratch/autobuild/multicore/charm/multicore-linux-x86_64/bin/../lib/libck.a(init.o):
In function `_initCharm(int, char**)':
/scratch/autobuild/multicore/charm/multicore-linux-x86_64/tmp/init.C:1293:
undefined reference to `CmiSetEMNcpyAckHandler'
/scratch/autobuild/multicore/charm/multicore-linux-x86_64/bin/../lib/libck.a(ckrdma.o):
In function `handleReverseEntryMethodApiCompletion(ncpystruct*)':
/scratch/autobuild/multicore/charm/multicore-linux-x86_64/tmp/ckrdma.C:639:
undefined reference to `CmiInvokeRemoteAckHandler'
collect2: error: ld returned 1 exit status

Change-Id: I8b05d7253458cd49d253d112e73e112873f312c2