Replace dependency scanning in tests/charm++/xcastredn with manual list
It was troublesome because it depends on the output to build
reductionBenchmark.decl.h, but MSVC's -showIncludes aborts on missing
files:

$ CL.EXE -nologo -W1 -EHsc -D_WINDOWS -DNOMINMAX -MT -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D__CHARMC__=1 -I../../../include -c -TpmyChareArray.C -showIncludes
myChareArray.C
Note: including file: c:\cygwin\home\ramos8\charm\multicore-win-x86_64\tests\charm++\xcastredn\myChareArray.h
Note: including file:  c:\cygwin\home\ramos8\charm\multicore-win-x86_64\tests\charm++\xcastredn\reductionBenchmark.h
c:\cygwin\home\ramos8\charm\multicore-win-x86_64\tests\charm++\xcastredn\reductionBenchmark.h(1): fatal error C1083: Cannot open include file: 'reductionBenchmark.decl.h': No such file or directory

Change-Id: Ia6322af3e11064c5eda710abe053d77233e7a46f